# Generated by Django 3.1.5 on 2021-01-05 11:48

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('price_initial', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount in (%)')),
                ('price_final', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.IntegerField(default=0)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Product Rating')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cover', models.ImageField(upload_to='product-cats')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('main_img', models.BooleanField(default=False, verbose_name='Is Main Picture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.productcategory'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=500, verbose_name='Last Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('slogan', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=500, verbose_name='Last Name')),
                ('birth_date', models.DateField()),
                ('photo', models.ImageField(upload_to='profiles')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('favorites', models.ManyToManyField(blank=True, default=None, related_name='favorites', to='estore.Product', verbose_name='Favorites')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_list', models.ManyToManyField(blank=True, default=None, related_name='wish_list', to='estore.Product', verbose_name='Wish List')),
            ],
        ),
    ]
