# Generated by Django 3.1.5 on 2021-01-05 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_recieved',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 5, 14, 5, 57, 417035, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='slug-def'),
            preserve_default=False,
        ),
    ]
