# Generated by Django 3.1.5 on 2021-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_auto_20210105_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtype',
            field=models.CharField(choices=[('m', 'men'), ('w', 'women')], default='m', max_length=2),
            preserve_default=False,
        ),
    ]
