# Generated by Django 3.1.5 on 2021-01-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_productcollection_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='max_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcollection',
            name='summary',
            field=models.CharField(default='text', max_length=1200),
            preserve_default=False,
        ),
    ]
