# Generated by Django 3.1.5 on 2021-01-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_auto_20210107_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='slug',
            field=models.SlugField(default='dd'),
            preserve_default=False,
        ),
    ]
