# Generated by Django 3.1.5 on 2021-01-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0009_productcollection_best_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='slider_collection',
            field=models.BooleanField(default=False),
        ),
    ]
